redis:
    image: redis
db:
    image: postgres
    volumes:
        - "./db_data:/var/lib/postgresql/data"
web:
    build: .
    links:
        - "db:postgres"
        - "redis:redis"
    volumes:
        - "./sentry-config:/home/user/.sentry"
        - "./tmp:/tmp"
    env_file: "./private/.env"
    ports:
        - "8080:9000"
celery:
    build: .
    links:
        - "db:postgres"
        - "redis:redis"
    volumes:
        - "./sentry-config:/home/user/.sentry"
        - "./tmp:/tmp"
    env_file: "./private/.env"
    command: "sentry celery worker -B"

